backend:
  name: git-gateway
  branch: master
media_folder: "public/media"
public_folder: "/media"
collections:
  - name: "work"
    label: "Work"
    folder: "src/work"
    create: true
    slug: "{{title}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Short Description", name: "short-desc", widget: "text" }
      - { label: "Featured Image", name: "feautred-image", widget: "image" }