backend:
  name: git-gateway
  branch: master
media_folder: "public/media"
public_folder: "/media"
collections:
  - name: "work" # Used in routes, e.g., /admin/collections/blog
    label: "Work" # Used in the UI
    folder: "src/work" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{title}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Project Title", name: "project_title", widget: "string"}
      - {label: "Project Description", name: "project_description", widget: "text"}
      - {label: "Featured Image", name: "featured_image", widget: "image", allow_multiple: "false", choose_url: "false"}
      - {label: "Project Highlights", name: "project_highlights", widget: "list", summary: '{{fields.image}}', field: {label: Image, name: hightlight_image, widget: image}}